Repository manzt/juv, pull requests merged in 2024-12, with the labels that each got.

#54 Support windows with `juv run`
  src/juv/_run_replace.py
  src/juv/_run_template.py
  tests/test_juv.py
Labels: enhancement

#55 Enable windows tests in CI
  .github/workflows/ci.yml
Labels: internal

#56 Force UTF-8 encoding when reading/writing text
  src/juv/_add.py
  src/juv/_run.py
  src/juv/_stamp.py
  tests/test_juv.py
Labels: enhancement

#57 Use TemporaryDirectoryIgnoreErrors in replacement template
  src/juv/_run_template.py
Labels: bug

#63 Upgrade minimum uv to v0.5
  pyproject.toml
  uv.lock
Labels: enhancement
